# Generated by Django 4.0.4 on 2022-05-30 12:22

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='', max_length=50)),
                ('kind', models.CharField(blank=True, default='', max_length=50)),
                ('products', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('customer_id', models.CharField(default='', max_length=50)),
                ('aoi', models.CharField(default='', max_length=50)),
                ('provider_name', models.CharField(default='', max_length=50)),
                ('promotion_id', models.CharField(default='', max_length=50)),
                ('order_date', models.DateTimeField(default='2022-05-30 12:22:00')),
                ('type', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=225)),
                ('promotion_id', models.CharField(max_length=225)),
                ('promotype', models.CharField(max_length=225)),
                ('start_date', models.DateTimeField(default=datetime.datetime.today)),
                ('end_date', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=250)),
                ('label', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
                ('api_key', models.CharField(max_length=250)),
                ('links', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=225)),
                ('service_id', models.CharField(max_length=225)),
                ('name', models.CharField(max_length=225)),
                ('type', models.CharField(max_length=225)),
                ('cost', models.IntegerField()),
                ('currencyunit', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=250)),
                ('serviceinfo', models.JSONField()),
                ('status', models.CharField(max_length=250)),
                ('startedAt', models.DateTimeField(default='2012-09-04 06:00:00.000000-08:00', null=True)),
                ('endedAt', models.DurationField(default='2012-09-04 06:00:00.000000-08:00', null=True)),
                ('type', models.CharField(max_length=250)),
                ('provider', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='micronet_app.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_id', models.CharField(max_length=250)),
                ('provider', models.CharField(default='', max_length=50)),
                ('aoi', models.JSONField()),
                ('products', models.JSONField()),
                ('est_cost', models.FloatField()),
                ('curr_unit', models.CharField(default='', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentUsername', models.CharField(max_length=100)),
                ('emailConfirmed', models.BooleanField(default=False)),
                ('reset_password', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(default='0', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=225)),
                ('name', models.CharField(max_length=225)),
                ('status', models.CharField(max_length=225)),
                ('createdAt', models.DateTimeField(default=datetime.datetime.today)),
                ('balanceUnit', models.CharField(max_length=225)),
                ('balance', models.IntegerField()),
                ('kind', models.CharField(max_length=225)),
                ('workspaceId', models.CharField(max_length=225)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micronet_app.provider')),
            ],
        ),
    ]
