# Generated by Django 4.0.4 on 2022-06-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micronet_app', '0004_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default='2022-06-01 12:58:03'),
        ),
    ]
